/**
 * Pure helpers for the bounded structural-apply path (TICKET-031). No I/O: deterministic ticket-ID
 * allocation, filesystem-safe slugging, and rendering of UNRELEASED (`status: sketched`,
 * `loop: false`, empty `spec`/`plan`) stub files for `derive-ticket` / `split-ticket` proposals,
 * plus the `needs-epic-wiring` triage item. The stubs are deliberately not loop-ready: a human
 * wires them into `epic.md` and releases them. `runApplyRefinement` owns all side effects.
 */
import type { Ticket } from "./types.ts";
import type { TriageItem } from "./triageInbox.ts";
import { buildTriageItem } from "./triageInbox.ts";

const TICKET_ID = /^TICKET-(\d+)$/;

/**
 * Allocate `count` sequential `TICKET-NNN` ids starting at `max(existing numeric ids) + 1`.
 * Non-`TICKET-NNN` ids are ignored when computing the max; an empty/all-ignored set starts at 1.
 * Deterministic and per-epic — the caller passes the epic's full ticket set.
 */
export function allocateTicketIds(existing: readonly Pick<Ticket, "id">[], count: number): string[] {
  const max = existing.reduce((m, t) => {
    const n = TICKET_ID.exec(t.id)?.[1];
    return n ? Math.max(m, Number(n)) : m;
  }, 0);
  return Array.from({ length: count }, (_, i) => `TICKET-${String(max + i + 1).padStart(3, "0")}`);
}

/** Cap (spec §5.3): keep filenames well under the 255-byte fs limit, preferring whole segments. */
const MAX_SLUG_LEN = 50;

/**
 * Lower-case, collapse non-alphanumeric runs to `-`, and trim leading/trailing `-`. Falls back to
 * `fallback` when the title yields no slug characters, so a created file name is always stable.
 * Capped at a stable short length (spec §5.3): truncated on whole hyphen-separated segment
 * boundaries when practical, always keeping at least the first segment (hard-sliced if that one
 * segment alone exceeds the cap).
 */
export function slugifyTicketTitle(title: string, fallback = "derived-ticket"): string {
  const raw = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  if (!raw) return fallback;
  if (raw.length <= MAX_SLUG_LEN) return raw;
  const segments = raw.split("-");
  let out = segments[0];
  for (let i = 1; i < segments.length; i++) {
    if (out.length + 1 + segments[i].length > MAX_SLUG_LEN) break;
    out = `${out}-${segments[i]}`;
  }
  return out.slice(0, MAX_SLUG_LEN).replace(/-+$/g, "");
}

function fmArray(values: readonly string[]): string {
  return `[${values.join(", ")}]`;
}

/** Render an unreleased `derive-ticket` stub. Intentionally NOT a full spec/plan. */
export function renderDerivedTicketStub(args: {
  id: string;
  title: string;
  rationale: string;
  dependsOn: readonly string[];
  runId: string;
}): string {
  return `---
id: ${args.id}
title: ${args.title}
status: sketched
spec:
plan:
loop: false
depends-on: ${fmArray(args.dependsOn)}
---

# ${args.id} - ${args.title}

> Autogenerated by TICKET-031 from a RefineBacklog \`derive-ticket\` proposal in \`${args.runId}\`. This is not loop-ready until a human wires it into \`epic.md\`, authors spec/plan, and flips \`loop: true\`.

## Sketch

${args.rationale}

## Human wiring needed

- Add \`${args.id}\` to \`epic.md\` \`tickets:\`.
- Add a dependency-table row with \`depends-on: ${fmArray(args.dependsOn)}\`.
- Decide whether this ticket should be released to the loop.
`;
}

/** Render an unreleased `split-ticket` child stub. The source ticket is NOT modified. */
export function renderSplitTicketStub(args: {
  id: string;
  title: string;
  rationale: string;
  sourceTicketId: string;
  inheritedDependsOn: readonly string[];
  runId: string;
}): string {
  return `---
id: ${args.id}
title: ${args.title}
status: sketched
spec:
plan:
loop: false
depends-on: ${fmArray(args.inheritedDependsOn)}
---

# ${args.id} - ${args.title}

> Autogenerated by TICKET-031 from a RefineBacklog \`split-ticket\` proposal in \`${args.runId}\`. This is not loop-ready until a human wires it into \`epic.md\`, authors spec/plan, and flips \`loop: true\`.

## Sketch

Source ticket: \`${args.sourceTicketId}\`

${args.rationale}

## Human wiring needed

- Decide whether \`${args.sourceTicketId}\` should be superseded or kept active.
- Add \`${args.id}\` to \`epic.md\` \`tickets:\` if accepted.
- Add a dependency-table row with inherited \`depends-on: ${fmArray(args.inheritedDependsOn)}\`.
- Rewire dependents only after human review.
`;
}

/** Build the `needs-epic-wiring` triage item for a materialized structural edit (existing shape). */
export function buildNeedsEpicWiringTriage(args: {
  ticketId: string;
  summary: string;
  detail: string;
}): TriageItem {
  return buildTriageItem({
    ticketId: args.ticketId,
    kind: "needs-epic-wiring",
    summary: args.summary,
    detail: args.detail,
    source: "backlog.refinement.apply",
  });
}
